import { useState, useEffect } from 'react';
import { toast } from 'sonner';
import { Dialog, DialogFooter } from '@/components/ui/Dialog';
import { FormField } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { DatePicker } from '@/components/ui/DatePicker';
import type { CreditCardDetails } from '@/types';
import { CardService } from '@/services/card.service';
import { normalizeEffectiveTo } from '@/types';
import { getCurrentDate } from '@/utils/date-utils';
import './CreateVersionModal.scss';

interface CreateVersionModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  referenceCardId: string;
  currentCard: CreditCardDetails | null;  // Can be null when creating first version
  onSuccess: (newVersionId: string) => void;
}

export function CreateVersionModal({
  open,
  onOpenChange,
  referenceCardId,
  currentCard,
  onSuccess,
}: CreateVersionModalProps) {
  const [formData, setFormData] = useState({
    VersionName: '',
    EffectiveFrom: '',
    EffectiveTo: '',
  });

  // For first version, we need to fetch card name data
  const [cardNameData, setCardNameData] = useState<{ CardName: string; CardIssuer: string } | null>(null);

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);

  // Initialize form data when component mounts
  // The parent uses a key prop to force remount when opening the modal
  useEffect(() => {
    setFormData({
      VersionName: currentCard ? '' : 'V1',  // Default to V1 for first version
      EffectiveFrom: getCurrentDate(),
      EffectiveTo: '',
    });
    setErrors({});

    // If no current card, fetch the card name data
    if (!currentCard && referenceCardId) {
      CardService.getCardName(referenceCardId).then((data) => {
        if (data) {
          setCardNameData({ CardName: data.CardName, CardIssuer: data.CardIssuer });
        }
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.VersionName.trim()) {
      newErrors.VersionName = 'Version name is required';
    }

    if (!formData.EffectiveFrom) {
      newErrors.EffectiveFrom = 'Effective from date is required';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validate()) {
      return;
    }

    setSubmitting(true);

    try {
      // Get card name and issuer from current card or fetched card name data
      const cardName = currentCard?.CardName || cardNameData?.CardName || '';
      const cardIssuer = currentCard?.CardIssuer || cardNameData?.CardIssuer || '';

      // Build the new version data
      let newVersionData: Partial<Omit<CreditCardDetails, 'id' | 'ReferenceCardId' | 'lastUpdated'>>;
      
      if (currentCard) {
        // Clone ALL fields from current card, then override specific fields
        // Destructure out fields we don't want to clone
        const { id, ReferenceCardId, lastUpdated, selected, isDefaultCard, ...clonedFields } = currentCard;
        
        newVersionData = {
          ...clonedFields,
          // Override with form values
          VersionName: formData.VersionName.trim(),
          effectiveFrom: formData.EffectiveFrom,
          effectiveTo: formData.EffectiveTo 
            ? normalizeEffectiveTo(formData.EffectiveTo) || clonedFields.effectiveTo
            : undefined, // Let server use sentinel value
          IsActive: false,
        };
      } else {
        // First version - minimal data, no card to clone from
        newVersionData = {
          VersionName: formData.VersionName.trim(),
          effectiveFrom: formData.EffectiveFrom,
          IsActive: false,
          CardName: cardName,
          CardIssuer: cardIssuer,
        };
        
        if (formData.EffectiveTo) {
          const normalized = normalizeEffectiveTo(formData.EffectiveTo);
          if (normalized) newVersionData.effectiveTo = normalized;
        }
      }

      const newVersionId = await CardService.createNewVersion(referenceCardId, newVersionData);

      toast.success('Version created successfully');
      onSuccess(newVersionId);
      onOpenChange(false);
    } catch (err: any) {
      console.error('Error creating version:', err);
      toast.error('Failed to create version: ' + err.message);
    } finally {
      setSubmitting(false);
    }
  };

  const formId = 'create-version-modal-form';

  return (
    <Dialog
      open={open}
      onOpenChange={onOpenChange}
      title="Create New Version"
      description="Create a new version of this card with different terms or benefits"
    >
      <form id={formId} onSubmit={handleSubmit} className="create-version-modal-form">
        {/* ID is autogenerated and will be shown in the sidebar after creation */}

        <FormField
          label="Version Name"
          value={formData.VersionName}
          onChange={(e) => setFormData({ ...formData, VersionName: e.target.value })}
          error={errors.VersionName}
          placeholder="e.g., V2, Updated 2024, etc."
        />

        <div className="info-box">
          <p>
            {currentCard 
              ? 'This will create a new version. You can edit the details after creation.'
              : 'This will create the first version for this card. You can add all card details after creation.'}
          </p>
        </div>

        <DatePicker
          label="Effective From"
          value={formData.EffectiveFrom}
          onChange={(value) => setFormData({ ...formData, EffectiveFrom: value })}
          error={errors.EffectiveFrom}
        />

        <DatePicker
          label="Effective To (optional)"
          value={formData.EffectiveTo}
          onChange={(value) => setFormData({ ...formData, EffectiveTo: value })}
          placeholder="Leave empty for ongoing"
          helperText="⚠️ IMPORTANT: If this version is currently active, leave this field BLANK."
        />

        <DialogFooter>
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={submitting}>
            Cancel
          </Button>
          <Button type="submit" form={formId} disabled={submitting}>
            {submitting ? 'Creating...' : 'Create Version'}
          </Button>
        </DialogFooter>
      </form>
    </Dialog>
  );
}
