import { useState, useEffect } from 'react';
import { toast } from 'sonner';
import { Dialog, DialogFooter } from '@/components/ui/Dialog';
import { FormField } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { DatePicker } from '@/components/ui/DatePicker';
import type { CreditCardDetails } from '@/types';
import { CardService } from '@/services/card.service';
import { normalizeEffectiveTo } from '@/types';
import './CreateVersionModal.scss';

interface CreateVersionModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  referenceCardId: string;
  currentCard: CreditCardDetails;
  onSuccess: () => void;
}

export function CreateVersionModal({
  open,
  onOpenChange,
  referenceCardId,
  currentCard,
  onSuccess,
}: CreateVersionModalProps) {
  const [formData, setFormData] = useState({
    VersionName: '',
    EffectiveFrom: '',
    EffectiveTo: '',
    setAsActive: false,
  });

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (open) {
      setFormData({
        VersionName: '',
        EffectiveFrom: new Date().toISOString().split('T')[0],
        EffectiveTo: '',
        setAsActive: false,
      });
      setErrors({});
    }
  }, [open]);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.VersionName.trim()) {
      newErrors.VersionName = 'Version name is required';
    }

    if (!formData.EffectiveFrom) {
      newErrors.EffectiveFrom = 'Effective from date is required';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validate()) {
      return;
    }

    setSubmitting(true);

    try {
      // Create a new version with blank values
      const newVersionData = {
        CardName: currentCard.CardName,
        CardIssuer: currentCard.CardIssuer,
        CardNetwork: currentCard.CardNetwork,
        CardDetails: '',
        CardImage: currentCard.CardImage,
        CardPrimaryColor: currentCard.CardPrimaryColor,
        CardSecondaryColor: currentCard.CardSecondaryColor,
        AnnualFee: null,
        ForeignExchangeFee: '',
        ForeignExchangeFeePercentage: null,
        RewardsCurrency: '',
        PointsPerDollar: null,
        VersionName: formData.VersionName.trim(),
        effectiveFrom: formData.EffectiveFrom,
        effectiveTo: normalizeEffectiveTo(formData.EffectiveTo),
        IsActive: formData.setAsActive,
      };

      await CardService.createNewVersion(referenceCardId, newVersionData);

      onSuccess();
      onOpenChange(false);
    } catch (err: any) {
      console.error('Error creating version:', err);
      toast.error('Failed to create version: ' + err.message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog
      open={open}
      onOpenChange={onOpenChange}
      title="Create New Version"
      description="Create a new version of this card with different terms or benefits"
    >
      <form onSubmit={handleSubmit} className="create-version-modal-form">
        {/* ID is autogenerated and will be shown in the sidebar after creation */}

        <FormField
          label="Version Name"
          value={formData.VersionName}
          onChange={(e) => setFormData({ ...formData, VersionName: e.target.value })}
          error={errors.VersionName}
          placeholder="e.g., V2, Updated 2024, etc."
        />

        <div className="info-box">
          <p>This will create a new version based on the current card configuration.</p>
        </div>

        <DatePicker
          label="Effective From"
          value={formData.EffectiveFrom}
          onChange={(value) => setFormData({ ...formData, EffectiveFrom: value })}
          error={errors.EffectiveFrom}
        />

        <DatePicker
          label="Effective To (optional)"
          value={formData.EffectiveTo}
          onChange={(value) => setFormData({ ...formData, EffectiveTo: value })}
          placeholder="Leave empty for ongoing"
          helperText="⚠️ IMPORTANT: If this version is currently active, leave this field BLANK."
        />

        <div className="checkbox-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={formData.setAsActive}
              onChange={(e) => setFormData({ ...formData, setAsActive: e.target.checked })}
            />
            <span>Set as active version</span>
          </label>
          <p className="checkbox-description">
            If checked, this version will be activated and other versions will be deactivated
          </p>
        </div>

        <DialogFooter>
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={submitting}>
            Cancel
          </Button>
          <Button type="submit" onClick={handleSubmit} disabled={submitting}>
            {submitting ? 'Creating...' : 'Create Version'}
          </Button>
        </DialogFooter>
      </form>
    </Dialog>
  );
}
